export const types = {

  AGREGAR_NOTA: "AGREGAR_NOTA",
  SET_ERROR: "SET_ERROR",
  OBTENER_NOTAS: "OBTENER_NOTAS",
  OBTENER_NOTA_A_ELIMINAR: "OBTENER_NOTA_A_ELIMINAR",
  ELIMINAR_NOTA: "ELIMINAR_NOTA",
  OBTENER_NOTA_A_EDITAR: "OBTENER_NOTA_A_EDITAR",
  EDITAR_NOTA: "EDITAR_NOTA",
};
